# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/136petrified/pone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/136petrified/pone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/136petrified/pone/CMakeFiles /home/136petrified/pone//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/136petrified/pone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named all_tests

# Build rule for target.
all_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_tests
.PHONY : all_tests

# fast build rule for target.
all_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/build
.PHONY : all_tests/fast

#=============================================================================
# Target rules for targets named ponetile_tests

# Build rule for target.
ponetile_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ponetile_tests
.PHONY : ponetile_tests

# fast build rule for target.
ponetile_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/build
.PHONY : ponetile_tests/fast

#=============================================================================
# Target rules for targets named ponecursor_tests

# Build rule for target.
ponecursor_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ponecursor_tests
.PHONY : ponecursor_tests

# fast build rule for target.
ponecursor_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/build
.PHONY : ponecursor_tests/fast

#=============================================================================
# Target rules for targets named ponegame_tests

# Build rule for target.
ponegame_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ponegame_tests
.PHONY : ponegame_tests

# fast build rule for target.
ponegame_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/build
.PHONY : ponegame_tests/fast

#=============================================================================
# Target rules for targets named ponegui_tests

# Build rule for target.
ponegui_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ponegui_tests
.PHONY : ponegui_tests

# fast build rule for target.
ponegui_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/build
.PHONY : ponegui_tests/fast

#=============================================================================
# Target rules for targets named poneboard_tests

# Build rule for target.
poneboard_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poneboard_tests
.PHONY : poneboard_tests

# fast build rule for target.
poneboard_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/build
.PHONY : poneboard_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/poneboard.o: src/poneboard.cpp.o
.PHONY : src/poneboard.o

# target to build an object file
src/poneboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/poneboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/poneboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/poneboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/poneboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/poneboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/poneboard.cpp.o
.PHONY : src/poneboard.cpp.o

src/poneboard.i: src/poneboard.cpp.i
.PHONY : src/poneboard.i

# target to preprocess a source file
src/poneboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/poneboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/poneboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/poneboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/poneboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/poneboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/poneboard.cpp.i
.PHONY : src/poneboard.cpp.i

src/poneboard.s: src/poneboard.cpp.s
.PHONY : src/poneboard.s

# target to generate assembly for a file
src/poneboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/poneboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/poneboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/poneboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/poneboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/poneboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/poneboard.cpp.s
.PHONY : src/poneboard.cpp.s

src/ponecursor.o: src/ponecursor.cpp.o
.PHONY : src/ponecursor.o

# target to build an object file
src/ponecursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponecursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponecursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponecursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponecursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponecursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponecursor.cpp.o
.PHONY : src/ponecursor.cpp.o

src/ponecursor.i: src/ponecursor.cpp.i
.PHONY : src/ponecursor.i

# target to preprocess a source file
src/ponecursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponecursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponecursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponecursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponecursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponecursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponecursor.cpp.i
.PHONY : src/ponecursor.cpp.i

src/ponecursor.s: src/ponecursor.cpp.s
.PHONY : src/ponecursor.s

# target to generate assembly for a file
src/ponecursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponecursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponecursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponecursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponecursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponecursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponecursor.cpp.s
.PHONY : src/ponecursor.cpp.s

src/ponegame.o: src/ponegame.cpp.o
.PHONY : src/ponegame.o

# target to build an object file
src/ponegame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegame.cpp.o
.PHONY : src/ponegame.cpp.o

src/ponegame.i: src/ponegame.cpp.i
.PHONY : src/ponegame.i

# target to preprocess a source file
src/ponegame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegame.cpp.i
.PHONY : src/ponegame.cpp.i

src/ponegame.s: src/ponegame.cpp.s
.PHONY : src/ponegame.s

# target to generate assembly for a file
src/ponegame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegame.cpp.s
.PHONY : src/ponegame.cpp.s

src/ponegate.o: src/ponegate.cpp.o
.PHONY : src/ponegate.o

# target to build an object file
src/ponegate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegate.cpp.o
.PHONY : src/ponegate.cpp.o

src/ponegate.i: src/ponegate.cpp.i
.PHONY : src/ponegate.i

# target to preprocess a source file
src/ponegate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegate.cpp.i
.PHONY : src/ponegate.cpp.i

src/ponegate.s: src/ponegate.cpp.s
.PHONY : src/ponegate.s

# target to generate assembly for a file
src/ponegate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegate.cpp.s
.PHONY : src/ponegate.cpp.s

src/ponegui.o: src/ponegui.cpp.o
.PHONY : src/ponegui.o

# target to build an object file
src/ponegui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegui.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegui.cpp.o
.PHONY : src/ponegui.cpp.o

src/ponegui.i: src/ponegui.cpp.i
.PHONY : src/ponegui.i

# target to preprocess a source file
src/ponegui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegui.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegui.cpp.i
.PHONY : src/ponegui.cpp.i

src/ponegui.s: src/ponegui.cpp.s
.PHONY : src/ponegui.s

# target to generate assembly for a file
src/ponegui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponegui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponegui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponegui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponegui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponegui.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponegui.cpp.s
.PHONY : src/ponegui.cpp.s

src/ponescript.o: src/ponescript.cpp.o
.PHONY : src/ponescript.o

# target to build an object file
src/ponescript.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponescript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponescript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponescript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponescript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponescript.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponescript.cpp.o
.PHONY : src/ponescript.cpp.o

src/ponescript.i: src/ponescript.cpp.i
.PHONY : src/ponescript.i

# target to preprocess a source file
src/ponescript.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponescript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponescript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponescript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponescript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponescript.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponescript.cpp.i
.PHONY : src/ponescript.cpp.i

src/ponescript.s: src/ponescript.cpp.s
.PHONY : src/ponescript.s

# target to generate assembly for a file
src/ponescript.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponescript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponescript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponescript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponescript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponescript.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponescript.cpp.s
.PHONY : src/ponescript.cpp.s

src/ponetile.o: src/ponetile.cpp.o
.PHONY : src/ponetile.o

# target to build an object file
src/ponetile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponetile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponetile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponetile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponetile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponetile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponetile.cpp.o
.PHONY : src/ponetile.cpp.o

src/ponetile.i: src/ponetile.cpp.i
.PHONY : src/ponetile.i

# target to preprocess a source file
src/ponetile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponetile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponetile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponetile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponetile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponetile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponetile.cpp.i
.PHONY : src/ponetile.cpp.i

src/ponetile.s: src/ponetile.cpp.s
.PHONY : src/ponetile.s

# target to generate assembly for a file
src/ponetile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/src/ponetile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/src/ponetile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/src/ponetile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/src/ponetile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/src/ponetile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/src/ponetile.cpp.s
.PHONY : src/ponetile.cpp.s

test/gtestmain.o: test/gtestmain.cpp.o
.PHONY : test/gtestmain.o

# target to build an object file
test/gtestmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/gtestmain.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/gtestmain.cpp.o
.PHONY : test/gtestmain.cpp.o

test/gtestmain.i: test/gtestmain.cpp.i
.PHONY : test/gtestmain.i

# target to preprocess a source file
test/gtestmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/gtestmain.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/gtestmain.cpp.i
.PHONY : test/gtestmain.cpp.i

test/gtestmain.s: test/gtestmain.cpp.s
.PHONY : test/gtestmain.s

# target to generate assembly for a file
test/gtestmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/gtestmain.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/gtestmain.cpp.s
.PHONY : test/gtestmain.cpp.s

test/poneboard_tests.o: test/poneboard_tests.cpp.o
.PHONY : test/poneboard_tests.o

# target to build an object file
test/poneboard_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/poneboard_tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/poneboard_tests.cpp.o
.PHONY : test/poneboard_tests.cpp.o

test/poneboard_tests.i: test/poneboard_tests.cpp.i
.PHONY : test/poneboard_tests.i

# target to preprocess a source file
test/poneboard_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/poneboard_tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/poneboard_tests.cpp.i
.PHONY : test/poneboard_tests.cpp.i

test/poneboard_tests.s: test/poneboard_tests.cpp.s
.PHONY : test/poneboard_tests.s

# target to generate assembly for a file
test/poneboard_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/poneboard_tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poneboard_tests.dir/build.make CMakeFiles/poneboard_tests.dir/test/poneboard_tests.cpp.s
.PHONY : test/poneboard_tests.cpp.s

test/ponecursor_tests.o: test/ponecursor_tests.cpp.o
.PHONY : test/ponecursor_tests.o

# target to build an object file
test/ponecursor_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponecursor_tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/ponecursor_tests.cpp.o
.PHONY : test/ponecursor_tests.cpp.o

test/ponecursor_tests.i: test/ponecursor_tests.cpp.i
.PHONY : test/ponecursor_tests.i

# target to preprocess a source file
test/ponecursor_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponecursor_tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/ponecursor_tests.cpp.i
.PHONY : test/ponecursor_tests.cpp.i

test/ponecursor_tests.s: test/ponecursor_tests.cpp.s
.PHONY : test/ponecursor_tests.s

# target to generate assembly for a file
test/ponecursor_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponecursor_tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponecursor_tests.dir/build.make CMakeFiles/ponecursor_tests.dir/test/ponecursor_tests.cpp.s
.PHONY : test/ponecursor_tests.cpp.s

test/ponegame_tests.o: test/ponegame_tests.cpp.o
.PHONY : test/ponegame_tests.o

# target to build an object file
test/ponegame_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegame_tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/ponegame_tests.cpp.o
.PHONY : test/ponegame_tests.cpp.o

test/ponegame_tests.i: test/ponegame_tests.cpp.i
.PHONY : test/ponegame_tests.i

# target to preprocess a source file
test/ponegame_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegame_tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/ponegame_tests.cpp.i
.PHONY : test/ponegame_tests.cpp.i

test/ponegame_tests.s: test/ponegame_tests.cpp.s
.PHONY : test/ponegame_tests.s

# target to generate assembly for a file
test/ponegame_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegame_tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegame_tests.dir/build.make CMakeFiles/ponegame_tests.dir/test/ponegame_tests.cpp.s
.PHONY : test/ponegame_tests.cpp.s

test/ponegui_tests.o: test/ponegui_tests.cpp.o
.PHONY : test/ponegui_tests.o

# target to build an object file
test/ponegui_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegui_tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/ponegui_tests.cpp.o
.PHONY : test/ponegui_tests.cpp.o

test/ponegui_tests.i: test/ponegui_tests.cpp.i
.PHONY : test/ponegui_tests.i

# target to preprocess a source file
test/ponegui_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegui_tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/ponegui_tests.cpp.i
.PHONY : test/ponegui_tests.cpp.i

test/ponegui_tests.s: test/ponegui_tests.cpp.s
.PHONY : test/ponegui_tests.s

# target to generate assembly for a file
test/ponegui_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponegui_tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponegui_tests.dir/build.make CMakeFiles/ponegui_tests.dir/test/ponegui_tests.cpp.s
.PHONY : test/ponegui_tests.cpp.s

test/ponetile_tests.o: test/ponetile_tests.cpp.o
.PHONY : test/ponetile_tests.o

# target to build an object file
test/ponetile_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponetile_tests.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/ponetile_tests.cpp.o
.PHONY : test/ponetile_tests.cpp.o

test/ponetile_tests.i: test/ponetile_tests.cpp.i
.PHONY : test/ponetile_tests.i

# target to preprocess a source file
test/ponetile_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponetile_tests.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/ponetile_tests.cpp.i
.PHONY : test/ponetile_tests.cpp.i

test/ponetile_tests.s: test/ponetile_tests.cpp.s
.PHONY : test/ponetile_tests.s

# target to generate assembly for a file
test/ponetile_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_tests.dir/build.make CMakeFiles/all_tests.dir/test/ponetile_tests.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ponetile_tests.dir/build.make CMakeFiles/ponetile_tests.dir/test/ponetile_tests.cpp.s
.PHONY : test/ponetile_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... all_tests"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... poneboard_tests"
	@echo "... ponecursor_tests"
	@echo "... ponegame_tests"
	@echo "... ponegui_tests"
	@echo "... ponetile_tests"
	@echo "... src/poneboard.o"
	@echo "... src/poneboard.i"
	@echo "... src/poneboard.s"
	@echo "... src/ponecursor.o"
	@echo "... src/ponecursor.i"
	@echo "... src/ponecursor.s"
	@echo "... src/ponegame.o"
	@echo "... src/ponegame.i"
	@echo "... src/ponegame.s"
	@echo "... src/ponegate.o"
	@echo "... src/ponegate.i"
	@echo "... src/ponegate.s"
	@echo "... src/ponegui.o"
	@echo "... src/ponegui.i"
	@echo "... src/ponegui.s"
	@echo "... src/ponescript.o"
	@echo "... src/ponescript.i"
	@echo "... src/ponescript.s"
	@echo "... src/ponetile.o"
	@echo "... src/ponetile.i"
	@echo "... src/ponetile.s"
	@echo "... test/gtestmain.o"
	@echo "... test/gtestmain.i"
	@echo "... test/gtestmain.s"
	@echo "... test/poneboard_tests.o"
	@echo "... test/poneboard_tests.i"
	@echo "... test/poneboard_tests.s"
	@echo "... test/ponecursor_tests.o"
	@echo "... test/ponecursor_tests.i"
	@echo "... test/ponecursor_tests.s"
	@echo "... test/ponegame_tests.o"
	@echo "... test/ponegame_tests.i"
	@echo "... test/ponegame_tests.s"
	@echo "... test/ponegui_tests.o"
	@echo "... test/ponegui_tests.i"
	@echo "... test/ponegui_tests.s"
	@echo "... test/ponetile_tests.o"
	@echo "... test/ponetile_tests.i"
	@echo "... test/ponetile_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

